# Generated by Django 5.2.6 on 2025-09-25 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(choices=[('monthly_1st', 'Monthly (1st)'), ('monthly_15th', 'Monthly (15th)'), ('bi_weekly', 'Bi-weekly'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('missing_po', 'Missing PO'), ('low_po_balance', 'Low PO Balance')], default='active', max_length=20)),
                ('last_billing_run', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.customer')),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.billingcycle')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.region')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'account_id')},
            },
        ),
    ]
