# Generated by Django 5.2.6 on 2025-09-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_billingcycle_region_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='cycle_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi_monthly', 'Bi-Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('annually', 'Annually')], max_length=20),
        ),
    ]
