# Generated by Django 5.2.6 on 2025-10-11 05:39

from django.db import migrations

from django.db import migrations

def create_default_projects(apps, schema_editor):
    """Create default project for each customer"""
    Customer = apps.get_model('customers', 'Customer')
    Project = apps.get_model('customers', 'Project')
    User = apps.get_model('auth', 'User')
    
    first_user = User.objects.first()
    
    for customer in Customer.objects.all():
        if not Project.objects.filter(customer=customer).exists():
            Project.objects.create(
                customer=customer,
                name='Default Project',
                code='DEFAULT',
                description='Auto-created during migration',
                created_by=first_user if first_user else customer.created_by,
                is_active=True
            )
            print(f"Created default project for customer: {customer.name}")

def reverse_func(apps, schema_editor):
    """Reverse migration"""
    Project = apps.get_model('customers', 'Project')
    Project.objects.filter(code='DEFAULT').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_populate_currencies_before_fk_change'),
    ]

    operations = [
        migrations.RunPython(create_default_projects, reverse_func),
    ]

