# Generated by Django 4.2.25 on 2025-10-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_swap_currency_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='project',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
