# Generated by Django 4.2.25 on 2025-10-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0009_swap_currency_fields'),
        ('rate_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratecard',
            options={},
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='rate_per_unit',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='ratecard',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='ratecard',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='entity',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='supplier',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ratecards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratecards', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('rate_type', models.CharField(choices=[('hourly', 'hourly'), ('day', 'day'), ('monthly', 'monthly'), ('fixed', 'fixed')], default='hourly', max_length=32)),
                ('rate_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='rate_cards.ratecard')),
            ],
        ),
    ]
