# Generated by Django 4.2.25 on 2025-10-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_cards', '0002_alter_ratecard_options_remove_ratecard_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='rate_type',
            field=models.CharField(default='hourly', max_length=32),
        ),
    ]
