# Generated by Django 5.2.6 on 2025-10-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_cards', '0003_alter_servicerate_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedicatedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band0_with', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band0_without', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band1_with', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band1_without', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band2_with', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band2_without', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band3_with', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band3_without', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band4_with', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('band4_without', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_services_rate', to='rate_cards.ratecard')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_4_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_sbn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_nbd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_2bd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_3bd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident_additional_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imac_2bd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imac_3bd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imac_4bd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_service_rate', to='rate_cards.ratecard')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_term_band0', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('short_term_band1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('short_term_band2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('short_term_band3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('short_term_band4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_term_band0', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_term_band1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_term_band2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_term_band3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('long_term_band4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_rate', to='rate_cards.ratecard')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_day_band0', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('full_day_band1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('full_day_band2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('half_day_band0', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('half_day_band1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('half_day_band2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_services_rate', to='rate_cards.ratecard')),
            ],
        ),
    ]
