# Generated by Django 4.2.25 on 2025-10-26 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate_cards', '0003_alter_servicerate_rate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerate',
            options={'verbose_name': 'Service Rate', 'verbose_name_plural': 'Service Rates'},
        ),
        migrations.AddField(
            model_name='servicerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rate_cards.ratecard'),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='rate_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='rate_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ScheduledRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('rate_type', models.CharField(blank=True, max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rate_cards.ratecard')),
            ],
            options={
                'verbose_name': 'Scheduled Rate',
                'verbose_name_plural': 'Scheduled Rates',
            },
        ),
        migrations.CreateModel(
            name='ProjectRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('rate_type', models.CharField(blank=True, max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rate_cards.ratecard')),
            ],
            options={
                'verbose_name': 'Project Rate',
                'verbose_name_plural': 'Project Rates',
            },
        ),
        migrations.CreateModel(
            name='DispatchRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('rate_type', models.CharField(blank=True, max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rate_cards.ratecard')),
            ],
            options={
                'verbose_name': 'Dispatch Rate',
                'verbose_name_plural': 'Dispatch Rates',
            },
        ),
        migrations.CreateModel(
            name='DedicatedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('rate_type', models.CharField(blank=True, max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_hours_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weekend_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rate_cards.ratecard')),
            ],
            options={
                'verbose_name': 'Dedicated Rate',
                'verbose_name_plural': 'Dedicated Rates',
            },
        ),
    ]
