# Generated by Django 5.2.6 on 2025-10-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_cards', '0004_dedicatedservices_dispatchservices_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedservices',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_services_rate', to='rate_cards.ratecard'),
        ),
        migrations.AlterField(
            model_name='dispatchservices',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_service_rate', to='rate_cards.ratecard'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rate', to='rate_cards.ratecard'),
        ),
        migrations.AlterField(
            model_name='scheduledservices',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_services_rate', to='rate_cards.ratecard'),
        ),
    ]
