# Generated by Django 4.2.25 on 2025-10-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_cards', '0004_alter_servicerate_options_servicerate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='rate_cards.ratecard'),
        ),
    ]
