# Generated by Django 5.2.6 on 2025-09-25 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0002_billingcycle_region_account'),
        ('purchase_orders', '0002_purchaseorderattachment_purchaseorderchangelog_and_more'),
        ('rate_cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRunAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='billing/attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRunLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ticket_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['work_date', 'description'],
            },
        ),
        migrations.AddField(
            model_name='billingrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.account'),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='billing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='billing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='billing_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('wizard', 'Wizard'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='billing/output/'),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='rate_card_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate_cards.ratecard'),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='tickets_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='tickets_file',
            field=models.FileField(blank=True, null=True, upload_to='billing/tickets/'),
        ),
        migrations.AlterField(
            model_name='billingrun',
            name='billing_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billingrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['status', 'created_at'], name='billing_bil_status_802c42_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['customer', 'created_at'], name='billing_bil_custome_1dde22_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrun',
            index=models.Index(fields=['account', 'created_at'], name='billing_bil_account_829126_idx'),
        ),
        migrations.AddField(
            model_name='billingrunattachment',
            name='billing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='billing.billingrun'),
        ),
        migrations.AddField(
            model_name='billingrunattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrunlineitem',
            name='billing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.billingrun'),
        ),
    ]
