# Generated by Django 5.2.6 on 2025-09-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorder_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POBalanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_percentage', models.IntegerField(choices=[(50, '50% Used'), (75, '75% Used'), (90, '90% Used - Low Balance')])),
                ('utilization_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_notifications', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('purchase_order', 'threshold_percentage')},
            },
        ),
    ]
