# Generated by Django 5.2.6 on 2025-09-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_purchaseorderpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('THB', 'Thai Baht')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('low_balance', 'Low Balance')], default='draft', max_length=20),
        ),
    ]
