# Generated by Django 5.2.6 on 2025-10-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_alter_purchaseorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='from_company',
            field=models.CharField(blank=True, help_text='Ordering company from PDF', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated grand total including tax', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Payment terms (e.g., NET 90)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requester',
            field=models.CharField(blank=True, help_text='Person who requested the PO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name from PDF', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_invoiced',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount already invoiced', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total tax', max_digits=15, null=True),
        ),
    ]
