# Generated by Django 5.2.6 on 2025-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_purchaseorder_from_company_purchaseorder_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(blank=True, help_text='e.g., FOB, CIF, EXW', max_length=100, null=True, verbose_name='Delivery Terms'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.CharField(blank=True, help_text='Department responsible for this purchase', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='items_description',
            field=models.TextField(blank=True, help_text='Detailed description of items/services', null=True, verbose_name='Items Description'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project_code',
            field=models.CharField(blank=True, help_text='Associated project code', max_length=50, null=True, verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_category',
            field=models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('software', 'Software'), ('hardware', 'Hardware'), ('consulting', 'Consulting'), ('maintenance', 'Maintenance')], default='services', max_length=20, verbose_name='Purchase Category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('capital', 'Capital Expenditure'), ('operational', 'Operational Expenditure'), ('project', 'Project Specific'), ('recurring', 'Recurring')], default='operational', max_length=20, verbose_name='Purchase Type'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warranty_period',
            field=models.IntegerField(default=0, help_text='Warranty period in months', verbose_name='Warranty Period (months)'),
        ),
    ]
