# Generated by Django 5.2.6 on 2025-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='warranty_period',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('THB', 'Thai Baht'), ('MYR', 'Malaysian Ringgit'), ('SGD', 'Singapore Dollar'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar')], default='USD', max_length=3),
        ),
    ]
