# Generated by Django 4.2.25 on 2025-10-23 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0009_remove_purchaseorder_purchase_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='purchase_orders/csvs/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('extraction_success', models.BooleanField(default=False)),
                ('extraction_errors', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Purchase Order CSV',
                'verbose_name_plural': 'Purchase Order CSVs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorderpdf',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderpdf',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='pobalancenotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'PO Balance Notification', 'verbose_name_plural': 'PO Balance Notifications'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Purchase Order Attachment', 'verbose_name_plural': 'Purchase Order Attachments'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderchangelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Purchase Order Change Log', 'verbose_name_plural': 'Purchase Order Change Logs'},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expiration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sdm',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Service Delivery Manager'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for API and external references', unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='work_done',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='USD', help_text='3-letter currency code (e.g., USD, EUR, GBP)', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='from_company',
            field=models.CharField(blank=True, help_text='Ordering company from CSV/PDF', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('low_balance', 'Low Balance'), ('expiring_soon', 'Expiring Soon'), ('fully_utilized', 'Fully Utilized')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name from CSV/PDF', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['uuid'], name='purchase_or_uuid_7ca960_idx'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderPDF',
        ),
        migrations.AddField(
            model_name='purchaseordercsv',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to='purchase_orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseordercsv',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
